### ISSUE TITLE
RetryHandler passes seconds instead of milliseconds to Guzzle delay option

### ISSUE THREAD

**Issue by hubipe** [microsoft/kiota-http-guzzle-php#9]
Hi,
I've came across a problem, where querying Graph API caused my program to „freeze“. I suspected retry handler to be a problem and dug into the code.
In the RetryHandler I see, that there is a Guzzle option delay set [here](https://github.com/microsoft/kiota-http-guzzle-php/blob/main/src/Middleware/RetryHandler.php#L89) and [here](https://github.com/microsoft/kiota-http-guzzle-php/blob/main/src/Middleware/RetryHandler.php#L118). The variable $delaySecs bears delay value in seconds, but Guzzle delay options [accepts delay parameter in milliseconds](https://docs.guzzlephp.org/en/stable/request-options.html#delay).

Shouldn't the delaySecs be passed in milliseconds rather than seconds?

**Comment by Ndiritu** [comment]
Thanks for catching this.

My thinking is to retain the abstraction as seconds since most people think of delay in terms of seconds? Thoughts?
